### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by Lvl4Sword** [Lvl4Sword/Killer#15]
Should probably have logging.

**Comment by MarkKoz** [comment]
Working on this.

**Comment by Lvl4Sword** [comment]
@MarkKoz Thank you.

**Comment by MarkKoz** [comment]
I think it would be good to add support for a [logging config](https://docs.python.org/3/library/logging.config.html). This we we don't have to make the decision what types of handlers to use or add a bunch of customisation options through command line arguments.

If we choose to do this, should it be JSON or YAML? The latter requires an external dependency but is cleaner in my opinion. This plays into my next question: would we merge the logger config and the main config or keep the separate? If they're merged, that would mean the main config likely also has to be the same format as the logger config: JSON or YAML.

**Comment by Lvl4Sword** [comment]
I'm find with YAML, and a separate config file.

**Comment by MarkKoz** [comment]
Would you be open to switching the main config to YAML later? The configparser format is fairly limiting and ugly. If so, would you still want the two configs kept separate? I was planning on eventually reworking the config code anyway cause it's messy.

Also, it turns out there's built in support for loading logger configs using the configparser format. However, it is an especially ugly format for logging configs so I will stick with YAML regardless.

**Comment by Lvl4Sword** [comment]
I trust your judgment. If one YAML file is better, go for it.

**Comment by MarkKoz** [comment]
Thank you. I don't even know if it is better yet. I can probably only make that decision once I've begun work or given any significant thought to what needs to be done with the current config.

I think I'll keep it separate for now so I can focus on the logging. I'll merge them later and try my best to design the logging config code in a way that wont be too hard to merge/migrate later.
