### ISSUE TITLE
Package killer for Debian 

### ISSUE THREAD

**Issue by 1989gironimo** [Lvl4Sword/Killer#31]
This would be a nice addition to PureOS from Purism, which is based on Debian, so it can be integrated for the Librem 5 for example.

**Comment by Lvl4Sword** [comment]
Would need a lot of assistance on this and other issues before this could happen. I'm also highly doubtful that we'd be able to package for the next Debian Stable (Buster) because according to https://release.debian.org/buster/freeze_policy.html the full freeze will happen March 12th. The project would need a considerable amount of work to be considered stable before then.

**Comment by HulaHoopWhonix** [comment]
We at Whonix are definitely interested in this too. Perhaps Patrick our lead dev can give you a few pointers to ease this process. He has custom scripts that help make packagin much smoother.

cc/ @adrelanos

**Comment by adrelanos** [comment]
See https://github.com/orjail/orjail/pull/27 for example how orjail got its debian packaging.

**Comment by Manouchehri** [comment]
Would be nice to have a Ubuntu PPA as well. =)
